### ISSUE TITLE
UX improvement - Switch to using Shift + "Two finger drag" (no click) on trackpads to Orbit around.

### ISSUE THREAD

**Issue by ss0git** [solvespace/solvespace#264] opened 2017-07-14 09:42 UTC
Proposed change to switch from Shift + "Two finger click and drag" to Shift + "Two finger drag" (no click) on trackpads to Orbit around.

### System information

SolveSpace version: 2.3

Operating system: OS X Sierra

### Expected behavior

Orbiting around using Shift + "Two fingers drag on trackpad" (no click) should work better. Pushing down to click is very cumbersome. You want to spin around the model like spinning an earth globe in school, effortless.

### Actual behavior

Shift + "Two fingers click and drag on trackpad" orbits around but not pushing down hard enough to click causes the app to Zoom.

To better see the change i made this table:

Current behaviour

_ | Pan | Zoom | Orbit
------------ | ------------- | ------------- | -------------
Flick fingers | _ | X  | _
Push down + Flick fingers | X | _  | X
Shift | _ | _  | X

Proposed behaviour

_ | Pan | Zoom | Orbit
------------ | ------------- | ------------- | -------------
Flick fingers | _ | X  | X
Push down + Flick fingers | X | _  | _
Shift | _ | _  | X

### Possible incompatibility with 

"Two fingers drag on trackpad" (mainly up and down) are used for Zooming (scrolling) now which is fine, but it might lead to a possible incompatibility.

To fix this we could use Shift as a separator. "Flick your fingers" to Zoom(scroll) (current functionality) and press Shift +  "Flick your fingers" to Orbit.

### Testing

I ran a couple of tests, for other reasons I have a setup that can produce or reverse the effect of any gestures and clicks, and the user experience will improve sensibly.

**Comment by whitequark** [comment] 2017-07-14 10:08
Duplicate of #68.

**Closed by whitequark** 2017-07-14 10:08 UTC
Labels: duplicate
