### ISSUE TITLE
wishlist -- make slvs format more git-friendly

### ISSUE THREAD

**Issue by ecc1** [solvespace/solvespace#300] opened 2017-10-30 17:39 UTC
I'm trying to keep successive iterations of designs in git repositories.  Whenever I open the design and change some aspect of the view, but not the object itself, the slvs representation changes, producing a lot of diffs that are not fundamental to the desgin. It would be nicer to somehow separate "essential geometry" from "presentation on the screen", perhaps saving them in separate files, or grouping them so that the diff would be clearer.

**Comment by whitequark** [comment] 2017-10-30 17:48
I agree. The new format, even though it is binary, will be designed in a way that lets you diff files by using git's "filter" feature.

**Comment by whitequark** [comment] 2018-07-12 12:37
Duplicate of #75.

**Closed by whitequark** 2018-07-12 12:37 UTC
Labels: duplicate
