### ISSUE TITLE
2.2/download version on gh crashes when symmetric constraint added

### ISSUE THREAD

**Issue by ohsix** [solvespace/solvespace#99] opened 2016-11-10 22:06 UTC
when i select the right most 2 vertices on the rectangle, and add symmetric constraint, solvepace crashes/exits on windows

i tested with linux on master but i can't spend time ruling it out atm.

[plasticsetup.slvs.zip](https://github.com/solvespace/solvespace/files/584545/plasticsetup.slvs.zip)

**Comment by whitequark** [comment] 2016-11-10 22:31
Dupe of https://github.com/solvespace/solvespace/issues/94; leaving open until 2.3 is released.

**Closed** 2016-12-24 02:07 UTC
Labels: duplicate
