### ISSUE TITLE
Lock-up on loading autosaved file, where dose solvespace put its auto save file? and how dose it name it ?

### ISSUE THREAD

**Issue by lachlanA** [solvespace/solvespace#677] opened 2020-08-15 04:18 UTC
### System information

SolveSpace version: <3.0~bc4924ae>

Operating system: 

### Additional information

I can't send the auto-saved file,   can't see where solve space puts it !

Lachlan

**Comment by phkahler** [comment] 2021-05-16 20:25
Duplicate of #678

**Closed by phkahler** 2021-05-16 20:25 UTC
Labels: question
