### ISSUE TITLE
placing points on lines in 3D makes them appear at strange places

### ISSUE THREAD

**Issue by wpwrak** [solvespace/solvespace#176] opened 2017-01-31 07:28 UTC
When placing a point on a line in 3D, it can appear at a different location than the one where I clicked. Here is an example showing a moderate displacement:
![point-in-3d-placement](https://cloud.githubusercontent.com/assets/1292352/22455681/edfe0bda-e76c-11e6-85b5-7561a6dabe03.png)

The model is
https://gitlab.com/anelok/mexp/raw/88480766568dc2ab7c00d2d0bea628c9895e554e/alt13/an-top.slvs

**Comment by whitequark** [comment] 2017-01-31 07:33
That's expected behavior, really, in any view that's not parallel to the line you're placing the point at.

**Comment by wpwrak** [comment] 2017-01-31 07:42
But why not place it where I asked, instead of making me search for where it may have ended up ? Especially if there are a lot of points (like in the example above), that can get quite tricky. Given that SolveSpace recognized the automatic point-on-line constraint, there is a valid position for that point in the immediate vicinity of the click location.

**Comment by Evil-Spirit** [comment] 2017-01-31 07:42
@whitequark, We need to implement ModifyToSatisfy for pt-on-line and call it when we are creating like for distances (since pt-on-line has hidden parameter which needs to be guessed when we just create constraint)

**Comment by whitequark** [comment] 2017-01-31 07:46
@Evil-Spirit ok

**Comment by Evil-Spirit** [comment] 2017-02-02 03:50
@whitequark, update here

**Comment by whitequark** [comment] 2017-02-05 10:14
Depends on #172

**Comment by Evil-Spirit** [comment] 2017-02-06 07:11
@whitequark, also here

**Comment by Evil-Spirit** [comment] 2017-02-06 07:19
@whitequark, sorry, not working here. wait.

**Comment by Evil-Spirit** [comment] 2017-02-06 07:26
@whitequark, ready here

**Comment by whitequark** [comment] 2017-02-06 14:21
Fixed in master.

**Closed by whitequark** 2017-02-06 14:21 UTC
Labels: enhancement, patch-available
