### ISSUE TITLE
Not initialized unnamed structures in Visual Studio

### ISSUE THREAD

**Issue by Evil-Spirit** [solvespace/solvespace#93] opened 2016-10-22 16:39 UTC
Some of the structures not initialized with zero even with brace initialization.

**Comment by Evil-Spirit** [comment] 2016-10-22 16:42
This is also can be included https://github.com/Evil-Spirit/solvespace/commit/e07404afb8f258c7935cc53cc875a6efe37fd391

**Comment by whitequark** [comment] 2016-11-17 10:09
The current master and opengl2 branches use the style like:

    OpenGl1Renderer() : camera(), lighting(), current() {}

I cannot reproduce the bug on master or opengl2, when built with MSVC locally, or on Appveyor. Can you confirm that this problem is not present? Or show where the uninitialized data ends?

**Comment by Evil-Spirit** [comment] 2016-11-17 11:07
@whitequark,
Yes, I still have this problem on master (GL Error 0x502).
This is because current.drawing not initialized with false

**Comment by whitequark** [comment] 2016-11-17 11:25
OK, I'll look further into it.

**Comment by whitequark** [comment] 2016-11-29 17:35
@Evil-Spirit May be similar to bc62478c0bc.

**Comment by Evil-Spirit** [comment] 2016-12-01 06:00
@whitequark, yes this bugs of the same nature.

**Comment by Evil-Spirit** [comment] 2017-03-02 01:28
@whitequark also, commints from whole branch Evil-Spirit/solvespace-master/commits/93-not-initialized

**Comment by whitequark** [comment] 2019-05-23 20:59
@Evil-Spirit I finally figured it out, should be fixed in 43a59e21.

**Closed by whitequark** 2019-05-23 20:59 UTC
Labels: internals
