### ISSUE TITLE
SolveSpace Crashed  when I draw a line

### ISSUE THREAD

**Issue by zhulaojianke** [solvespace/solvespace#984] opened 2021-04-01 13:23 UTC
### System information

- **SolveSpace version:**3.0~36719c62. 

- **Operating system:**  Win7 Ultimate Edition sp1

### Expected behavior

Only draw a line

### Actual behavior

It pops up a message window.
![image](https://user-images.githubusercontent.com/16543111/113299843-e2a2d400-932f-11eb-87ae-a509499a8522.png)

### Additional information

Sorry, I can't give you any files. When I click to generate a debug report, the solvespace quits itself.

**Comment by zhulaojianke** [comment] 2021-04-01 13:31
It seems only occurs on chinese interface, when I change the language to english, there is nothing go wrong.
![image](https://user-images.githubusercontent.com/16543111/113301372-893ba480-9331-11eb-97b3-8ebde4c59f39.png)

**Comment by zhulaojianke** [comment] 2021-04-01 13:35
When I close the "check sketch for closed contour", this crash also be avoided, even in chinese interface.

**Comment by phkahler** [comment] 2021-04-01 21:07
@zhulaojianke  The chinese translation has not been well tested. When I merged the pull request all I did was verify that the menus switch to chinese, which I can't read. It never occurred to me that a "bad" character might crash the program.

This is really easy to recreate - draw a single line segment with language set to chinese.

Sounds like it may be an issue with the on-sketch vector font not handling something correctly. We may need to change the chinese text for the "not a closed contour....." message.  Unfortuantely the submitter has not responded since the translation was submitted.

If you want to help that would be great, otherwise I'll try deleting the chinese version of that message and leave it english. That's better than crashing!

**Comment by zhulaojianke** [comment] 2021-04-02 05:25
I don't think it's a translation problem，it seems to be a character encoding problem, because when I put a comment on the workplace and input chinese character such as “试试看”, it also return a wrong display.
![image](https://user-images.githubusercontent.com/16543111/113382580-69999000-93b4-11eb-9fc7-23f5825df299.png)
It seems any chinese character will be displayed wrong here.
To display chinese character correctly, I suggest to use these character encoding, such as [GB18030]简体中文（UTF-PRC）, [GBK]Windows Chinese Simplified（CP 936）or GB-2312, [MACCHINESESIMP]MacChineseSimp.

I don't know how to program or sinicalize, and I feel that's all I can do to help. I'm so sorry.

**Comment by phkahler** [comment] 2021-04-02 21:55
@zhulaojianke  The problem is the on-sketch text display uses a special vector font. We can't change the font or encoding without making huge changes to how text is drawn on the sketch. Many characters are missing from that font and they usually display as the same symbol. Looking at the translation file I see the following:

not closed contour, or not all same style!
未闭合轮廓，或样式不一致!

If I copy those chinese characters into a comment constraint SolveSpace will crash (even in english). If I only copy the first part up to the comma, it will not crash but only 2 of the symbols are shown correctly with the "missing glyph" showing for the other 3.

I'm happy to revert this one string to english, or change it to something else chinese if you can find a suitable text that will display properly (try entering text in a comment constraint.  Then post that text here on github and I'll update it).

**Comment by zhulaojianke** [comment] 2021-04-03 05:08
OK! I find it! Replace the SBC case comma to a DBC case comma, or do not use SBC case punctuation mark in the alarm message or comment.
For example, I input the same message using DBC case comma in the comment
![image](https://user-images.githubusercontent.com/16543111/113469052-0f183680-947d-11eb-8d3d-94427bdcb6a0.png)
and then
![image](https://user-images.githubusercontent.com/16543111/113469059-1e977f80-947d-11eb-9169-89ca9e4804b5.png)
It no longer crashes, although it still didn't display correctly.

**Comment by zhulaojianke** [comment] 2021-04-03 05:19
I have tried other inputting contained SBC case punctuation mark, the SolveSpace crashed too.
For example, I input these using SBC case comma, and press enter key
![image](https://user-images.githubusercontent.com/16543111/113469276-f3ae2b00-947e-11eb-8477-cc386eba67a0.png)
and then...
![image](https://user-images.githubusercontent.com/16543111/113469300-12142680-947f-11eb-8a23-a90061450827.png)

**Comment by phkahler** [comment] 2021-04-03 15:59
@zhulaojianke  there are some characters missing from the font. Can you find a way to translate the message that makes sense, doesnt crash solvespace, and displays correctly?

**Comment by phkahler** [comment] 2021-04-03 17:25
I am closing this issue after changing the comma. The message no longer crashes.

**Closed by phkahler** 2021-04-03 17:25 UTC
