### ISSUE TITLE
Locales switching does NOT work for "Property Browser"

### ISSUE THREAD

**Issue by Symbian9** [solvespace/solvespace#999] opened 2021-04-04 18:00 UTC
### System information

- **SolveSpace version:** `3.0~` https://github.com/solvespace/solvespace/commit/2df786e7415501c748f34741aa1d5c561e730814
- **Operating system:** Debian 10 buster

### Expected behavior

1. Switching locales should take effect not only *main window*, but also *"Property Browser" window*;
2. Remember selected locale for next SolveSpace session.

### Actual behavior

1. Switching locales should actually takes effect only *main window* — *"Property Browser" window* instead always is English-only;
2. Selected locale does not used for next startup — instead each SolveSpace session starts in English.

### Additional information

<details><summary>Screenshots (taken after each locale switch)</summary>

![pic.1](https://i.imgur.com/is8o7ZH.png)

![pic.2](https://i.imgur.com/PHeXmNm.png)

![pic.3](https://i.imgur.com/3VDIWnE.png)

</details>

**Comment by phkahler** [comment] 2021-04-04 18:40
The property browser is not coded in a way that allows localization. I agree that it would be an improvement, but it will have to wait for a rewrite of all that code. There are no specific plans to do that yet.

**Comment by phkahler** [comment] 2021-04-04 18:54
Duplicate of #319

**Closed** 2021-04-04 21:36 UTC
Labels: UI, duplicate

**Comment by ruevs** [comment] 2021-04-07 08:54
In fact the even older issue is https://github.com/solvespace/solvespace/issues/112
