### ISSUE TITLE
I can not copy between two or more open windows/projects of Solvespace.

### ISSUE THREAD

**Issue by dadoprom** [solvespace/solvespace#1439] opened 2023-12-24 11:42 UTC
### System information

- **SolveSpace version:** 
- 3.1~486e43a4
- **Operating system:** 
-  Lubuntu 22.04.3 LTS x86_64 

### Expected behavior

If two instances of Solvespace are running, I would like to be able to copy between them.

### Actual behavior

Is not possible, nothing happens...

**Comment by phkahler** [comment] 2023-12-24 15:45
Duplicate of #845

**Closed by phkahler** 2023-12-24 15:45 UTC
