### ISSUE TITLE
Add STEP (.STP) Import

### ISSUE THREAD

**Issue by aaulia** [solvespace/solvespace#911] opened 2021-01-27 01:06 UTC
Add ability to import STEP (.STP) file to SolveSpace.

**Comment by ruevs** [comment] 2021-01-27 09:22
Very unlikely to happen.

**Comment by phkahler** [comment] 2021-01-27 11:43
Duplicate of #88

**Comment by phkahler** [comment] 2021-01-27 12:09
@aaulia the biggest problem with STEP is reading the format. It's a huge specification, although we could probably discard a lot of it.

**Comment by aaulia** [comment] 2021-01-27 13:11
> @aaulia the biggest problem with STEP is reading the format. It's a huge specification, although we could probably discard a lot of it.

Is there any plan to implement this at all? I mean, I respect the developer decision one way or another. I will still use Solvespace whenever I can. But its inability to work with other format really limit what it can be used for. 

> Duplicate of #88  

`2016`, wow hahaha. Ok so this issue have been talked about for a long time. I understand.

**Closed** 2021-01-27 13:12 UTC
Labels: STEP, duplicate

**Comment by phkahler** [comment] 2021-01-27 14:19
@aaulia There isn't a plan to implement it, but we would like the ability to at least "link" step files into an assembly.  SolveSpace currently doesn't support direct editing of NURBS surfaces (a lot of people don't realize that), but linking step as a fixed part would still be valuable.

**Comment by aaulia** [comment] 2021-01-27 14:48
> @aaulia There isn't a plan to implement it, but we would like the ability to at least "link" step files into an assembly. SolveSpace currently doesn't support direct editing of NURBS surfaces (a lot of people don't realize that), but linking step as a fixed part would still be valuable.

I agree, that would still be very valuable.
