### ISSUE TITLE
No real RC1 tarball

### ISSUE THREAD

**Issue by vuokko** [solvespace/solvespace#874] opened 2021-01-06 10:04 UTC
### System information

SolveSpace version: 3.0RC1

Operating system: OpenBSD -current

### Expected behavior

Extracting source tar ball should be buildable

### Actual behavior

github is providing automatic tar balls. (snapshots of source) and extlibs aren't populated.
Trying to populate them with git ends up in:
git submodule update --init extlib/libdxfrw extlib/mimalloc
fatal: not a git repository (or any parent up to mount point /)

### Additional information

The instructions to build on OpenBSD are so simple and I decided to try write a port for solvespace and do some testing. 
So that's why requirement of source release.

**Comment by ppd** [comment] 2021-01-06 10:25
I suppose it's possible to publish another tarball asset including the submodules. Or we could provide a script that downloads the submodules without requiring the tarball to include a git repository.

**Comment by ruevs** [comment] 2021-01-16 07:50
https://github.com/solvespace/solvespace/issues/772#issuecomment-730461961

**Comment by phkahler** [comment] 2021-05-16 20:21
Closing as a duplicate of #1028 which is not specific to RC1.

**Closed by phkahler** 2021-05-16 20:21 UTC
