### ISSUE TITLE
how to run the opensource files and run the program in visual studio 2019 

### ISSUE THREAD

**Issue by hasanqo** [solvespace/solvespace#722] opened 2020-09-27 22:45 UTC
it canot be run i want to modify the sketchflat or solve space some one guide me

**Comment by phkahler** [comment] 2020-09-28 01:35
Duplicate of issue #672 

You may have better luck with Visual Studio 2015.

**Closed by phkahler** 2020-09-28 01:35 UTC

**Comment by hasanqo** [comment] 2020-09-28 01:38
Thanks alot i figured finally how to build the program and run it
successfully. Best regards

في الاثنين، ٢٨ أيلول، ٢٠٢٠ ٤:٣٥ ص phkahler <notifications@github.com> كتب:

**Comment by phkahler** [comment] 2020-09-28 13:05
> Thanks alot i figured finally how to build the program and run it successfully. Best regards

Did you get it to compile in VS 2019? If so, is there anything that should change in the code or the instructions?

**Comment by hasanqo** [comment] 2020-09-28 13:09
No i just compile it with visual studio 2019. Best regards

في الاثنين، ٢٨ أيلول، ٢٠٢٠ ٤:٠٥ م phkahler <notifications@github.com> كتب:
