### ISSUE TITLE
Allow to set range for distance/angle constrains

### ISSUE THREAD

**Issue by Harvie** [solvespace/solvespace#418] opened 2019-05-20 23:27 UTC
Currently i can only set absolute distance between two points (or angle between two lines).
But for me it would be usefull if i can specify min/max value (or both).

Eg:

```
<10
>10
<=10
>=10
10-20
```

![image](https://user-images.githubusercontent.com/276504/58058002-7bc70800-7b67-11e9-9204-42a25f489238.png)

**Comment by whitequark** [comment] 2019-05-20 23:30
Duplicate of #81.

**Closed by whitequark** 2019-05-20 23:30 UTC
Labels: duplicate
