### ISSUE TITLE
Symmetry constraint crashes app if no mainline defined

### ISSUE THREAD

**Issue by pretentiousgit** [solvespace/solvespace#146] opened 2016-12-31 14:14 UTC
### System information
SolveSpace version: 2.2
Operating system: MacOSX El Cap 10.11.4

### Expected behavior

Drew two circles, set equal radius constraint => Expected to be equal, were equal
Set Symmetry constraint => Expected circles to set selves symmetrical through center line of workspace, since no main line was drawn

Alternately: A warning that no main center line has been selected

### Actual behavior
Set Symmetry constraint =>  SolveSpace silently crashes

### Additional information

This was a fresh file and a fresh drawing with nothing in it on a fresh install.

**Comment by whitequark** [comment] 2016-12-31 14:21
Duplicate of #94, fixed in version 2.3 (https://github.com/solvespace/solvespace/releases/tag/v2.3).

**Closed by whitequark** 2016-12-31 14:21 UTC
Labels: duplicate
