### ISSUE TITLE
Miscolored fonts in 2D PDF view

### ISSUE THREAD

**Issue by baryluk** [solvespace/solvespace#541] opened 2020-01-15 17:35 UTC
### System information

Commit 16c5fa6889202f2059b52c4a89599910541dd1a0

Operating system: Debian testing, and64

### Expected behavior

Consistent colors of text / fonts in the PDF export

### Actual behavior

I added text to some sketches using Menu: Constrain -> Comment (;), and while viewing in solvespace and export to PNG works, PDF export has some issues:

![solvespace-pdf-font-colors](https://user-images.githubusercontent.com/110322/72456804-4984ad80-37bd-11ea-81a6-772ee301231c.png)

This is a cropped screenshot as viewed by MATE Atril PDF viewer.

**Comment by whitequark** [comment] 2020-01-15 18:21
Duplicate of #518.

**Closed by whitequark** 2020-01-15 18:21 UTC
Labels: duplicate
