### ISSUE TITLE
Not fully constrained shape when fast dragging with mouse

### ISSUE THREAD

**Issue by starsolaris** [solvespace/solvespace#676] opened 2020-08-14 21:33 UTC
### System information

SolveSpace version: 3.0 bc4924ae

Operating system: Windows 10

### Expected behaviour
When i try to move fully constrained shape by dragging upper-left vertex, nothing should happen, regardless of whether I move the mouse fast or slow.
![image](https://user-images.githubusercontent.com/715636/90294053-34c0e300-de8e-11ea-9854-53aa07717803.png)

### Actual behaviour
When I move the shape behind the vertex slowly, it doesn't move; if I move it quickly, it moves.
![image](https://user-images.githubusercontent.com/715636/90294260-ae58d100-de8e-11ea-88a1-e10747c5fc86.png)

### Additional information
[quad.zip](https://github.com/solvespace/solvespace/files/5077359/quad.zip)

**Comment by phkahler** [comment] 2020-08-14 23:25
This is a known behaviour. When it flips the other direction all the constraints are still satisfied, so in some sense it is not fully constrained, but it takes effort to make it flip.

**Comment by whitequark** [comment] 2020-08-15 08:32
Yeah, duplicate of #76.

**Closed by whitequark** 2020-08-15 08:32 UTC
Labels: duplicate

**Comment by starsolaris** [comment] 2020-08-15 11:18
I understand that second case is fully satisfy constraints also, but different options depending on the speed of movement of the mouse is very annoying. (i cannot flip shape if i will move mouse with slow speed)

**Comment by whitequark** [comment] 2020-08-15 11:19
I'm aware that it's annoying but you must understand that properly fixing this requires a significant redesign of the constraint system.
