### ISSUE TITLE
Not all solid edges exported for 2D VIEW if "Draw occluded lines" 

### ISSUE THREAD

**Issue by Symbian9** [solvespace/solvespace#397] opened 2019-04-25 11:03 UTC
### System information

SolveSpace version: 3.0~ https://github.com/solvespace/solvespace/commit/ce0b130d6ceb2145c8150eecbffe7380948899d4

Operating system: Debian 9.x

### Expected behavior

All lines should be exported to 2D view (PDF, etc.) if set "Draw occluded lines"

### Actual behavior

If set "Draw occluded lines" then only some edges of lathed object exported on 2D View (PDF).

Here is lathed object as shown in SolveSpace

![pic.1](https://i.imgur.com/0s5eU8Y.png)

And here is resulted 2D View exported in PDF

![pic.2](https://i.imgur.com/PnHdTfA.png)

### Additional information

For bugs, please attach a savefile that shows the problematic behavior.
You can attach `.slvs` files by archiving them into a `.zip` first.

**Comment by phkahler** [comment] 2020-09-08 23:25
Can not reproduce. It looks like the silhouette edges are missing in the @Symbian9 image. Are they possibly there but drawn in white? (does changing the background color work?

BTW I tried all 3 variations of the occluded line toolbar button and they all worked for me. I did notice that the hover-text tells what it will switch to after you press it, now what it is currently set to. Doesn't matter because all 3 options produced the same edges in the .pdf as what I had on screen.

Can you attach a file that exhibits the problem?

**Comment by phkahler** [comment] 2020-09-22 15:59
Closing as not reproducible.

**Closed by phkahler** 2020-09-22 15:59 UTC
Labels: bug
