### ISSUE TITLE
Crash with Unmatched regex

### ISSUE THREAD

**Issue by Evil-Spirit** [solvespace/solvespace#153] opened 2017-01-12 15:04 UTC
### System information
Appears after adding translations.
Windows 7 x64, MS VS 2013 compiler

### Expected behavior

Should work

### Actual behavior

Crash on running tests and running SolveSpace.exe

### Additional information

File E:\SolveSpaceWork\solvespace_dxf\src\resource.cpp, line 488, function SolveSpace::ASCIIReader::ExpectRegex:
Assertion 'Unmatched regex' failed: ((TryRegex(re, m)) == false).

**Comment by whitequark** [comment] 2017-01-12 16:27
This seems like an MSVC-related bug, or maybe \r\n issue. Can you look?

**Comment by Evil-Spirit** [comment] 2017-01-12 17:33
@whitequark, OK

**Comment by lomatus** [comment] 2017-01-13 04:12
Vote +1
Appears after adding translations.
Windows 7 x64/x86, MS VS 2015 compiler

**Comment by whitequark** [comment] 2017-01-14 00:35
I cannot reproduce this one myself with either MSVS2013 or MSVS2015, weird.

@lomatus would that be a zh_CN translation? I am very interested in that one.

**Comment by whitequark** [comment] 2017-01-14 02:51
Should be fixed in master.

**Closed by whitequark** 2017-01-14 02:51 UTC
Labels: bug, Win32

**Comment by whitequark** [comment] 2017-01-14 03:39
@Evil-Spirit btw there is an unmerged ru_RU translation already, don't bother

**Comment by Evil-Spirit** [comment] 2017-01-14 03:55
@whitequark, OK
