### ISSUE TITLE
Performance drop with a step and repeat rotating

### ISSUE THREAD

**Issue by hinell** [solvespace/solvespace#1214] opened 2022-02-08 09:14 UTC
```
Vector::WithMagnitude(1) of zero vector! 
Generate::REGEN (for bounding box) took 15720 ms
Generate::REGEN took 31897 ms
Generate::ALL (for bounding box) took 16577 ms
Generate::ALL took 33203 ms
Generate::DIRTY (for bounding box) took 15852 ms
Generate::DIRTY took 32006 ms
Generate::ALL (for bounding box) took 16113 ms
Generate::ALL took 32466 ms
```

See a linked model below for reproduction. The log is above. The culprit is the `step and repeat rotating` group. If I apply it (e.g. 20 rotations) to any complex sketch (say 20 construction + 10 actual lines) it slows down significantly so it remains unresponsive for a few minutes 

**Note:** The `Vector::WithMagnitude(1) of zero vector!` string above is repeated after every line many times. I have omitted it for the sake of readability.

## Image & file
* [gear-32-2.zip]
<img alight="right" width="256px" src="https://user-images.githubusercontent.com/8136158/152892690-f2b694a6-f75c-406d-9742-25ba814c46cd.png" />

[gear-32-2.zip]: https://github.com/solvespace/solvespace/files/8019594/gear-32-2.zip
### System information
- **Operating system:** Linux Kubuntu (plasmashell 5.21.4)
- **SolveSpace version:** 3.0.rc2+repack1-3
### Expected behavior
* Lighting fast overall performance

### Actual behavior
* Very slow step and repeat rotating. It also slows down:
* * solid suppression (browser)
* * toggling control points visibility (browser) 
* * workplane switch (browser)
* * creation and delete of a sketch in a new workplane (editor window and browser)

**Comment by ruevs** [comment] 2022-02-08 11:45
https://github.com/solvespace/solvespace/issues/1186#issuecomment-1032277333
https://github.com/solvespace/solvespace/issues/1186#issuecomment-1032472416

**Comment by ruevs** [comment] 2022-02-08 11:47
@hinell try an edge build.
https://github.com/solvespace/solvespace#via-automated-edge-builds

Since you are on Linux try the edge build from the SnapStore https://github.com/solvespace/solvespace#via-snap-store

Is it still slow?

Can we use your model in a potential future benchmark? Under what license?

**Comment by ruevs** [comment] 2022-02-08 11:47
On current [master](https://github.com/solvespace/solvespace/commit/d8b5281f) changing the repeat from 1 to **_64_** in `g00b-rotate` takes `Generate::DIRTY took 2871 ms` ;-)

[gear-64-2.zip](https://github.com/solvespace/solvespace/files/8022949/gear-64-2.zip)

![Gear64](https://user-images.githubusercontent.com/15338069/152970072-41d5fde4-6c14-430a-8eff-e6c566fccf54.png)

By the way there are better ways to draw the teeth of the gear ;-)
https://solvespace.com/forum.pl?action=viewthread&parent=3911&tt=1633767543
https://solvespace.com/forum.pl?action=viewthread&parent=2477&tt=1541434762
https://solvespace.com/forum.pl?action=viewthread&parent=916&tt=1439146696
https://solvespace.com/forum.pl?action=viewthread&parent=291&tt=1413300884
https://github.com/solvespace/solvespace/issues/550#issuecomment-655814031
etc.

**Comment by hinell** [comment] 2022-02-08 14:54
@ruevs Thanks, I will try to do that.

Thanks for the links as well. Turns out, there is a nice article in the [wikipedia on that](https://en.wikipedia.org/wiki/Involute_gear). Cool shit.

**Comment by Symbian9** [comment] 2022-02-08 15:10
> On current `master` changing the repeat from `1` to `64` in `g00b-rotate` takes `Generate::DIRTY took 2871 ms`

@ruevs, as for me, ***NURBS solid difference fails*** in your  SLVS-file from [gear-64-2.zip](https://github.com/solvespace/solvespace/files/8022949/gear-64-2.zip)

![Screenshot_2022-02-08_14-11-36](https://user-images.githubusercontent.com/13188580/152984939-4352f349-9c02-4d1b-b560-46b4bead9138.png)

**Comment by Symbian9** [comment] 2022-02-08 15:12
> Turns out, there is a nice article in the [wikipedia on that](https://en.wikipedia.org/wiki/Involute_gear). Cool shit.

JFTR, Here is collection of tutorials for making "Involute Gear" in SolveSpace:

- https://homehack.nl/solvespace-involute-gear/

**Comment by ruevs** [comment] 2022-02-08 15:36
The performance with "Hide edges of solid model" is practically the same `Generate::DIRTY took 2723 ms` - this model is solver limited. Not OpenGL, triangulation etc...

As for the NURBS problem I do see the red edges as well, but after pressing ESC the solid is water tight/valid and we have much simpler models reproducing this. Thus it is not interesting.

**Comment by hinell** [comment] 2022-02-08 20:14
@Symbian9 

> Can we use your model in a potential future benchmark? Under what license?

Sure. As long as you are not trying make profits out it. Thanks for checking it out anyway. ;)

Looks like I'm going to build solvespace from scratch because I also have discovered a few nutty cases that simply hang entire app. No memory leaks however. Surprisingly.

**Comment by ruevs** [comment] 2022-02-08 20:31
> a few nutty cases that simply hang entire app.

If you find reproducible "nutty cases" open issues.

>  No memory leaks however. Surprisingly.

Quite a bit of work has gone into it over the years. You'll find that "edge" is usually as stable as any release.

**Comment by Symbian9** [comment] 2022-02-08 21:35
> `@Symbian9`
> > Can we use your model in a potential future benchmark? Under what license?
> Sure. As long as you are not trying make profits out it. Thanks for checking it out anyway. ;)

Guess, it was reply to @ruevs question ;)

**Comment by ruevs** [comment] 2022-02-10 10:22
So @hinell did you try? Can I we close this now?

**Comment by hinell** [comment] 2022-02-10 18:55
@ruevs Give me a bit more time.

**Comment by hinell** [comment] 2022-02-10 22:32
@ruevs Yeah, feel free to close this. 
I can confirm that with newer version it became much more responsive. At least it doesn't freeze to an unusable degree for now.

**Closed** 2022-02-10 22:31 UTC
Labels: duplicate, documentation, solver, waiting-on-reporter, performance

**Comment by hinell** [comment] 2022-02-10 22:41
@ruevs Yeah, feel free to close this. 
I can confirm that with a newer version it became much more responsive.
At least it doesn't freeze beyond unusable state for now.
