### ISSUE TITLE
Tangential circles in a rectangle can break contour filling

### ISSUE THREAD

**Issue by Natronium** [solvespace/solvespace#303] opened 2017-11-18 23:06 UTC
### System information

SolveSpace version: 3.0~13695be0
Operating system: Gentoo Linux

### Expected behavior
The contour gets filled in

### Actual behavior
This happens:
![](https://user-images.githubusercontent.com/25114018/32985401-d0a80062-cc87-11e7-8fef-e8c6c91101e3.png)

Additionally, extruding the shape creates naked edges at the points where that same circle touches its neighbours:
![](https://user-images.githubusercontent.com/25114018/32985436-fdd419bc-cc88-11e7-8c4f-b360aa044ed9.png)

All of this is accompanied by the same error that whitequark pointed out in #296:
```
couldn't find an ear! fail
```
however, unlike #296, enabling 'force NURB surfaces to triangle mesh' doesn't fix the issue in either case.
### Additional information

The file in question: [tangent-circles-break-contour-fill.zip](https://github.com/solvespace/solvespace/files/1485089/tangent-circles-break-contour-fill.zip)

**Comment by whitequark** [comment] 2017-11-19 04:07
Yeah, needs a better triangulation algorithm.

**Comment by Evil-Spirit** [comment] 2017-11-19 07:25
Tangential should be handled as error like countour self-intersection. In case of tangential the result mesh will be non-manifold (this is bad for some reason)

**Comment by whitequark** [comment] 2018-07-12 12:35
> Tangential should be handled as error like countour self-intersection.

I agree. Do you think you can write the fix? I'm not good with numeric code...

**Comment by Evil-Spirit** [comment] 2018-07-12 13:22
This not look hard to me.

**Comment by phkahler** [comment] 2020-06-25 02:33
Initially could not reproduce using the attached .slvs file of similar construction.
[Tangent_Circle_Test.zip](https://github.com/solvespace/solvespace/files/4828794/Tangent_Circle_Test.zip)

But... It happens if the construction lines attached to the upper right circle-center are H and V constrained. In that configuration 4 Beziers end at a single point where the circles meet. Pinging @ruevs because he's got some interest in NURBS issues and this is a case where something 2D breaks down prior to any surface creation.

**Comment by phkahler** [comment] 2020-08-14 20:01
PR #675 only addresses the first part of this, so I'm not going to close this yet. The naked edges remain.

**Comment by whitequark** [comment] 2020-08-15 08:39
@phkahler Did you close this by accident?

**Comment by phkahler** [comment] 2020-08-15 12:53
@Whitequark Yes by accident, I thought I deleted the reference from the PR before I merged it but this still closed. It's still a good case of naked edge problems though.

**Comment by phkahler** [comment] 2020-09-11 19:46
I've submitted issue 696 which I believe covers the second problem reported here. I'd like to close this, as the title does not match the second issue which has nothing to do with the contour filling and everything to do with coincident edges.

**Closed** 2020-09-13 19:18 UTC
Labels: bug
