### ISSUE TITLE
Algebraic constraints

### ISSUE THREAD

**Issue by baryluk** [solvespace/solvespace#542] opened 2020-01-16 14:40 UTC
This is a feature request.

I would like to be able to add linear and non-linear constraints. Either as a side note on the sketch, with a symbolic names referencing dimensions, or for some constraints of the form: 'B = something_without_B' directly in the constrain line segment/distance/angle/radius.

![constraints1](https://user-images.githubusercontent.com/110322/72534009-020a2a00-386e-11ea-8e9b-745185c4243b.png)

Ability to add implicit constraints between dimensions (ones which can't be inverted algebraically) would also be really cool:

![constraints-implicit](https://user-images.githubusercontent.com/110322/72534022-0a626500-386e-11ea-97fb-eba731020022.png)

Right now some of these types of constraints are already possible, but require a lot of auxilary construction lines and understanding a lot about geometry. Some are super tedious. `B=3*A` can be done relatively easy. But doing `B=3.1*A` will be supper annoying for example, despite the solver being able to handle algebraic constraints under the hood.

The added benefit of explicit and implicit algebraic constraints is that beyond easier reading of the sketch for documentation, it also reduces number of variables and points / lines in the sketch, which should lead to a better performance. The supported algebraic operations in the sketch should be double differntiable, which should make things easier.

Custom functions (macros), might be an extended feature, for the future. Example: `f(A, B, C) := A*A + B*B - C*C + A*B/C`, then use it as `f(K, L, M/2) = f(X, Y, f(Z, 2.0, K)) + 3.0` for example, or in many other constraints. That might be somehow useful, but is only a syntactic sugar for manually typing things.

I don't know if there is any CAD out there that allows doing things exactly like this. But it would make solvespace extremely powerful :D

Obviously if constraints are really hard numerically, or oscillating / non-smooth, solvespace is free to give up and blame the user :D No need to be perfect or handle all possible things, as that is simply not possible in non-linear solving and optimization.

Similarly in the initial implementation, there is no need to check for dimensional units I think. I.e. user is free to pass linear dimension to the trigonometric function, or construct constraints with mismatched units, like `log(A) + A*B = C`, where all A, B, C are in normal linear units (`mm` for example). It can be detected statically by the program, but is only an extra bonus for the future.

The same could be done for inequality constraints, either on a single variable or on the expression. They could be put in the sketch for easy view and reference.

**Comment by whitequark** [comment] 2020-01-16 19:36
Duplicate of #77, #81, etc.

**Closed by whitequark** 2020-01-16 19:36 UTC

**Comment by baryluk** [comment] 2020-01-16 20:39
@whitequark Sorry for the duplicate and thanks for pointing me to the existing bugs. I did a search before posting, but I didn't see these bugs.

Cheers.
