### ISSUE TITLE
Selected the wrong edge

### ISSUE THREAD

**Issue by starsolaris** [solvespace/solvespace#769] opened 2020-10-22 17:22 UTC
### System information

SolveSpace version: 3.0~2adf5dec

Operating system: Windows 10

1. create rectangle 
2. extrude
![image](https://user-images.githubusercontent.com/715636/96907263-ae370c00-14a3-11eb-9e6b-bbbf756dfe78.png)
3. select some edge
![image](https://user-images.githubusercontent.com/715636/96907431-e2aac800-14a3-11eb-9f18-f310351ae737.png)

### Expected behavior

should be selected nearest edge
![image](https://user-images.githubusercontent.com/715636/96907553-066e0e00-14a4-11eb-8893-05546855469d.png)

### Actual behavior

far edge will be selected 
![image](https://user-images.githubusercontent.com/715636/96907519-fce4a600-14a3-11eb-938c-1c18c31e4f56.png)

**Comment by phkahler** [comment] 2020-10-22 20:10
This is a duplicate of #521

**Closed by phkahler** 2020-10-22 20:10 UTC
Labels: UI
